#!/bin/bash

cat >> .config << 'EOF'

CONFIG_DEVEL=y

CONFIG_CCACHE=y

CONFIG_KERNEL_DEBUG_INFO=y
CONFIG_KERNEL_DEBUG_INFO_BTF=y
CONFIG_KERNEL_DEBUG_INFO_REDUCED=n

CONFIG_PACKAGE_dae=y

CONFIG_PACKAGE_kmod-sched-bpf=y
CONFIG_PACKAGE_kmod-veth=y
CONFIG_PACKAGE_kmod-xdp-sockets-diag=y

EOF
